/*
 * Date
 * Name
 * Program
 */

/**
 *
 * @author kikag
 */
public class frmEncryptionProgram extends javax.swing.JFrame {

    /**
     * Creates new form frmEncryptionProgram
     */
    public frmEncryptionProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblDecrypted = new javax.swing.JLabel();
        lblEncripted = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDecrypted = new javax.swing.JTextField();
        btnEncrypt = new javax.swing.JButton();
        txtEncryptedFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEncrypted = new javax.swing.JTextField();
        btnDecrypt = new javax.swing.JButton();
        txtDecryptedFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("----Encrypt/Decript Software----");

        lblDecrypted.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblDecrypted.setForeground(new java.awt.Color(204, 0, 0));
        lblDecrypted.setText("----------------*(;;;decrypted;;;)*----------------");

        lblEncripted.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lblEncripted.setForeground(new java.awt.Color(204, 0, 0));
        lblEncripted.setText("----------------*(ae=[_][jk+'/.;)*----------------");

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("----Encrypt/Decript Software----");

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Enter a decrypted message and it will be encrypted");

        txtDecrypted.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        btnEncrypt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnEncrypt.setForeground(new java.awt.Color(204, 0, 0));
        btnEncrypt.setText("ENCRYPT");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        txtEncryptedFinal.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        txtEncryptedFinal.setText("Encrypted message will be displayed here...");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Enter an encrypted message and it will be decrypted");

        txtEncrypted.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        btnDecrypt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnDecrypt.setForeground(new java.awt.Color(204, 0, 0));
        btnDecrypt.setText("DECRYPT");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        txtDecryptedFinal.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        txtDecryptedFinal.setText("Decrypted message will be displayed here...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnEncrypt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(txtDecrypted)
                                .addComponent(txtEncryptedFinal)
                                .addComponent(txtDecryptedFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDecrypted)
                                    .addGap(16, 16, 16))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEncripted)
                                    .addGap(20, 20, 20)))
                            .addComponent(txtEncrypted, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(btnDecrypt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEncripted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtDecrypted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncrypt)
                .addGap(18, 18, 18)
                .addComponent(txtEncryptedFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEncrypted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDecrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDecryptedFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecrypted)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String reverseMessage (String Msg){
        String revMessage = "";
        for (int i = Msg.length() - 1; i >= 0; i = i - 1) {
            revMessage = revMessage + Msg.charAt(i);
        }
        return revMessage;
    }
    
    public String caesarCypher (String origMessage){
        char tempChar;
        int tempAscii;
        String encMessage = "";
        for (int i = 0; i < origMessage.length(); i++){
            
            tempChar = origMessage.charAt(i);
            tempAscii = (int)tempChar;
            tempAscii = tempAscii + 3;
            tempChar = (char)tempAscii;
            encMessage = encMessage + tempChar;
        }
        
        return encMessage;
    }
    
    public String caesarCypherReversed (String origMessage){
        char tempChar;
        int tempAscii;
        String encMessage = "";
        for (int i = 0; i < origMessage.length(); i++){
            
            tempChar = origMessage.charAt(i);
            tempAscii = (int)tempChar;
            tempAscii = tempAscii - 3;
            tempChar = (char)tempAscii;
            encMessage = encMessage + tempChar;
        }
        
        return encMessage;
    }
    
    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        // get message from user
        String decryptedMessage = txtDecrypted.getText();
        
        int length = decryptedMessage.length();
        //chek if message is larger than 30 characters long
        if (length >= 31){
            txtEncryptedFinal.setText("This message is too long. Please enter a message shorter than 31 characters.");
        } else{
            
        //Call Reversing method
        String reversedString = reverseMessage(decryptedMessage);
        
        //bump reversed message's characters by 3
        String encryptedMessage = caesarCypher(reversedString);
        
        //print encrypted message
        txtEncryptedFinal.setText(encryptedMessage);
        }
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // get message from user
        String encrypted = txtEncrypted.getText();
        //reverse caesar cypher
        String decrypted1 = caesarCypherReversed(encrypted);
        //reverse String once again
        String fullydecrypted = reverseMessage(decrypted1);
        //print the result
        txtDecryptedFinal.setText(fullydecrypted);
    }//GEN-LAST:event_btnDecryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEncryptionProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEncryptionProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEncryptionProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEncryptionProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEncryptionProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDecrypted;
    private javax.swing.JLabel lblEncripted;
    private javax.swing.JTextField txtDecrypted;
    private javax.swing.JTextField txtDecryptedFinal;
    private javax.swing.JTextField txtEncrypted;
    private javax.swing.JTextField txtEncryptedFinal;
    // End of variables declaration//GEN-END:variables
}
